#!/bin/bash
#########################################
# VOGEL Thierry                         #
#                                       #
# V0.1 14/10/2012 version HPUX          #
#                                       # 
# V0.2 10/01/2013 version linux         #
# v0.3 12/01/2013 ceci est le script maj#
#########################################
####IDEES#####
#cette lib contient des fonctions specifiques
#ainsi que les variables d'environnement
#############
#####variables#####
#fichier de configuration
cRep=/home/thierry/exercices/projets/maj/.conf
lib_maj=lib_maj
libg=libG
#fichiers systemes
rep_boot=/boot
fboot="initramfs-linux-fallback.img initramfs-linux.img vmlinuz-linux"
rep_sboot=/media/sboot
dsboot=/dev/sdb1
lv_root=/dev/vg00/lvol0
#convention
ancien=old
CONT=0
ERR_SYSTEME=251
ERR_USAGE=252
####preparation######
source $cRep/$lib_maj
source $cRep/$libg
####fonctions######
function action
{
if [ "$1" -eq 1 ];then 
	echo "split"
	split_mirror
elif [ "$1" -eq 2 ];then 
	echo "valide"
	valide_change
elif [ "$1" -eq 3 ];then
	echo "retour"
	retour_phase1
elif [ "$1" -eq 4 ];then
	echo "retour2"
	retour_phase2
else retour 1 "choix de l'utilisateur"
fi

}
function menu
{
dialog --help-button --title "Script de retour sur maj" \
--menu "faite votre choix:" 15 55 5 \
1 "split avec trackchanges" \
2 "valider le changement" \
3 "retour arriere phase 1" \
4 "retour arriere phase 2" 2>menu_maj.$$
choix=$(cat menu_maj.$$)
set $choix
if [ "$1" == "HELP" ];then
	choix=$2
	dialog --msgbox "pas d'aide disponible :) - a bientot" 30 80 2>/dev/null;
	menu
else
	choix=$1
fi
action $choix
}
trap "rm menu_maj.$$" 0 1 2 5 15
#trap "rm menu_maj.$$" INT QUIT
menu
exit 0
